rtc-op5326448v1:
  service:
    enable: true
    type: "ClusterIP"
    ports:
      - name: "http"
        port: 8080
      - name: "curio"
        port: 8081
  curio:
    enable: true
    tag: "0.5.5"
    environments:
      - name: "CURIO_SIGLA_APLICACAO"
        value: "rtc"
      - name: "CURIO_CACHE_CONFIGURACAO_IIB"
        value: "redis.iib-cache-config"
      - name: "CURIO_CACHE_CONFIGURACAO_IIB_ID"
        value: "iib:configuracao:k8s-integracao"
      - name: "CURIO_IIB_LOG_LEVEL"
        value: "INFO"
      - name: "CURIO_OP_PROVEDOR"
        value: "br.com.bb.rtc.operacao:Op5326448-v1:3.0.0-SNAPSHOT"
      - name: "KUMULUZEE_LOGS_LOGGERS0_NAME"
        value: ""
      - name: "KUMULUZEE_LOGS_LOGGERS0_LEVEL"
        value: "info"
    resources:
      requests:
        cpu: 350m
        memory: 350Mi
      limits:
        cpu: 500m
        memory: 500Mi
    livenessProbe:
        httpGet:
          path: /health/live
          port: 8081
        initialDelaySeconds: 120
        timeoutSeconds: 30
        failureThreshold: 10
    readinessProbe:
        httpGet:
          path: /health/ready
          port: 8081
        initialDelaySeconds: 120
        timeoutSeconds: 30
        failureThreshold: 10

  deployment:
    enable: true
    imagePullSecrets: "atfregistry"
    replicaCount: 1
    tolerations: []
    containers:
      repository: "atf.intranet.bb.com.br:5001/bb"
      image: "rtc/rtc-op5326448v1"
      tag: "1.0.1"
      imagePullPolicy: "IfNotPresent"
      ports:
        - name: "app"
          containerPort: 8080
      livenessProbe:
        httpGet:
          path: "/health"
          port: 8080
        initialDelaySeconds: 300
        timeoutSeconds: 30
        failureThreshold: 10
      resources:
        requests:
          memory: "350Mi"
          cpu: "350m"
        limits:
          memory: "700Mi"
          cpu: "700m"
      environments:
        - name: "QUARKUS_DATASOURCE_URL"
          valueFrom:
            secretKeyRef:
              name: "db2"
              key: "DB_CONNECTION_URL"
        - name: "QUARKUS_DATASOURCE_USERNAME"
          valueFrom:
            secretKeyRef:
              name: "db2"
              key: "DB_USER"
        - name: "QUARKUS_DATASOURCE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "db2"
              key: "DB_PASSWORD"
        - name: "QUARKUS_DATASOURCE_DRIVER"
          valueFrom:
            secretKeyRef:
              name: "db2"
              key: "DB_DRIVER"
  serviceMonitor:
    enable: true
    monitorNamespace: "rtc-monitor"
    labels:
      monitor: "rtc"
    selectorMatchLabels: {}
    endpoints:
      - port: "app"
        interval: "10s"
      - port: "curio"
        interval: "10s"